### ISSUE TITLE
APK availability

### ISSUE THREAD

**Issue by IzzySoft** [1Coin-FinanceTracker/1CoinClient#11]
Would you consider making the APK available outside of Google's walled garden? Currently it's not possible to obtain it without using their proprietary store and its app. Not even Exodus could [extract the APK](https://reports.exodus-privacy.eu.org/en/analysis/535840/) for a scan ("APK could not be downloaded"). Open Source should be made available in the open IMHO :wink: And while the code is available under a free license, not everyone can compile or even has a build environment set up.

Thanks in advance!

**Comment by VitalyPeryatin** [comment]
@IzzySoft Thank you for your suggestion! This is very important to us.

We will add a link to download APK file surely. We will add it to the README.md approximately by the end of this week

**Comment by IzzySoft** [comment]
Ideally, [tag your releases](https://github.com/1Coin-FinanceTracker/1CoinClient/releases) and attach the APKs there. That's the first place folks usually look at if they want to get them.

**Comment by VitalyPeryatin** [comment]
@IzzySoft 
We added ["Releases" block](https://github.com/1Coin-FinanceTracker/1CoinClient/releases). There is you can download apps for Android and MacOS versions (MacOS version not optimized now). 

Is this problem solved? Can I close the issue?

**Comment by IzzySoft** [comment]
Thanks! And yes, as the APK is available, this issue is solved.
