### ISSUE TITLE
Функция скрытия баланса в интерфейсе

### ISSUE THREAD

**Issue by FUZIK** [1Coin-FinanceTracker/1CoinClient#94]
На данный момент приложение не даёт возможности скрыть баланс в интерфейсе

Предлагаю добавить функцию накладывающую цензурирующую маску на текст с балансом
Нужна маска накладывающая размытие или пиксилизацию

В качестве события влючения/выключения функции можно использовать клик по балансу из topbar или данные с акселерометра для распознавания переворота телефона

* В Compose, есть [BlurEffect](https://developer.android.com/reference/kotlin/androidx/compose/ui/graphics/RenderEffect) работающий на Android 12 и позднее
Такое решение не подходит, значит нужно писать свой эффект

**Comment by FUZIK** [comment]
Я возьму эту фичу в реализацию, сначала я сделаю пикселизацию и активацию по клику
@VitalyPeryatin

**Comment by VitalyPeryatin** [comment]
@FUZIK Добрый день! Подскажи, получилось ли реализовать этот функционал? Если нет, то мы могли бы переоткрыть Issue на английском языке и предоставить публичный готовый дизайн для реализации этой фичи, чтобы другие разработчики имели возможно реализовать эту фичу. Если фича уже готова, не могли бы открыть PR?

**Comment by VitalyPeryatin** [comment]
Закрываю Issue в связи в неактуальностью, в дальнейшем при запросе фичи от пользователей переоткрою Issue на английском языке
